### ISSUE TITLE
Update or remove `sig/amqp-client.rbs`

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/amqp-client.rb#15]
What can `sig/amqp-client.rbs` be used for? Do we need it in the repo? Currently I think it is a bit outdated (after running `typeprof lib/amqp-client.rb > sig/amqp-client.rbs` there's quite the diff)

https://github.com/cloudamqp/amqp-client.rb/blob/9b0662288d96b57cf331a494b469e23273886315/sig/amqp-client.rbs#L1-L4

**Comment by carlhoerberg** [comment]
fixed
