### ISSUE TITLE
Support `connection_timeout` below 1 second

### ISSUE THREAD

**Issue by PuloV** [cloudamqp/amqp-client.rb#23]
Is there a way to configure the client to have `connection_timeout` that is below 1 second?
For example something like: 
```ruby
uri = "amqp://guest:guest@localhost"
amqp_client_options = { connection_timeout: 0.5 }
AMQP::Client.new(uri, **amqp_client_options).connect
```
If not supported, do you have it on the roadmap, and if yes, when could we expect it?

**Comment by carlhoerberg** [comment]
Have you tried `500.milliseconds`?

**Comment by PuloV** [comment]
@carlhoerberg do you refer to the `in_milliseconds` method as the one suggested by you is not implemented?
```ruby
3.0.5 :146 > 500.milliseconds
(irb):146:in `<main>': undefined method `milliseconds' for 500:Integer (NoMethodError)
Did you mean?  in_milliseconds
```

Also, I do believe that since it parses the time to int
```ruby
3.0.5 :145 > 1.in_milliseconds
 => 1000 
```
and the lib is described to accept integers, it's not acting as expected and it's setting the timeout to be `1000` seconds.

So to get back on the question, is the `connection_timeout: 0.5` valid approach, or is there any other valid approach to define timeout below 1 second?

**Comment by carlhoerberg** [comment]
Oh, sorry, thought the issue was on amqp-client.cr haha. Will look into why a float isn't accepted in this lib.

**Comment by carlhoerberg** [comment]
Probably just replace `.to_i` with `.to_f` here: https://github.com/cloudamqp/amqp-client.rb/blob/main/lib/amqp/client/connection.rb#L409

**Comment by carlhoerberg** [comment]
And note that it's `connect_timeout`. not `connection_timeout`
